AdminClient:
  client_id: oai-admin-boris-producer
OAI:
  set: driver
  timestampUTC: '2019-01-25T01:01:01Z'
  url: http://boris.unibe.ch/cgi/oai2
  metadataPrefix: oai_dc
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-boris-producer
Topic:
  name: BORIS

