AdminClient:
  client_id: oai-admin-idslu-producer
OAI:
  set: SWISSBIB-FULL-OAI
  timestampUTC: '2019-01-25T01:01:01Z'
  url: http://ilu.zhbluzern.ch/OAI
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-idslu-producer
Topic:
  name: IDSLU
