AdminClient:
  client_id: oai-admin-kbtg-producer
OAI:
  timestampUTC: '2020-03-21T01:01:01Z'
  url: http://netbiblio.tg.ch/frau-kb4-sru/oai/notices
  metadataPrefix: marcxml
Processing:
  Default:
    stoppageTime: '2019-01-16T12:55:24Z'
Producer:
  client_id: oai-kbtg-producer
Topic:
  name: cc-kbtg
