AdminClient:
  client_id: oai-admin-libib-producer
OAI:
  set: SWISSBIB-FULL-OAI
  timestampUTC: '2019-02-14T01:01:01Z'
  url: http://aleph.lbfl.li/OAI
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-libib-producer
Topic:
  name: LIBIB

