AdminClient:
  client_id: oai-admin-sgbn-producer
OAI:
  set: SWISSBIB-FULL-OAI
  timestampUTC: '2019-01-25T01:01:01Z'
  url: https://aleph.sg.ch/OAI
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-sgbn-producer
Topic:
  name: SGBN
