AdminClient:
  client_id: oai-admin-vaud-school-producer
OAI:
  set: SwisOAI
  timestampUTC: '2019-02-14T01:01:01Z'
  url: https://eu01.alma.exlibrisgroup.com/view/oai/41BCULAUSA_SCHOOL/request
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-vaud-school-producer
Topic:
  name: VAUD
