AdminClient:
  client_id: edu-admin-zem-producer
  bootstrap_servers: localhost:9092,localhost:9093,localhost:9094

EDU:
  token: Fcu6J7vK8IzlUOMHsMTqs57Xgfahpu
  timestampUTC: '2019-05-16T01:01:01Z'
  url: https://api.marketcircle.net
  auth_file: zem_auth.yaml
  time_to_refresh_token: 2500
  code_data_provider: 'ZEM'

  #lastproject: 862127

Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: edu-zem-producer
  bootstrap_servers: localhost:9092,localhost:9093,localhost:9094

Topics: cc-zem-open

Topic:
  name: cc-zem-open

Consumer:
  #bootstrap_servers: sb-uka3:9092,sb-uka4:9092,sb-uka5:9092,sb-uka6:9092
  bootstrap_servers: localhost:9092,localhost:9093,localhost:9094
  client_id: zem_consumer_clie
  auto_offset_reset: earliest
  consumer_timeout_ms: 10000

Logging:
  name: default-cc-not-used
  path: /basedir/logs/times.log
  errpath: /basedir/logs/error.log
  config: /basedir/configs/logs/cc.config.yaml

ES:
  #hosts: "sb-ues5.swissbib.unibas.ch:8080"
  hosts: "localhost:8080"
  index: metisgym5
  active: True

Transformations:
  enrich_persons:
    - '24047000':
        url: https://www.swissbib.ch/Search/Results?lookfor=%22Langenegger,%20Andr%C3%A9%22&type=Author
    - '19402000':
        url: https://www.swissbib.ch/Search/Results?lookfor=%22Capaul,%20Roman%22&type=Author

  keywords:
    - Kaderkurse:
        url: https://www.swissbib.ch/Search/Results?join=AND&bool0%5B%5D=OR&lookfor0%5B%5D=schulleitung&lookfor0%5B%5D=schulverwaltung&lookfor0%5B%5D=schulorganisation&lookfor0%5B%5D=schulentwicklung&lookfor0%5B%5D=schulleiter&type0%5B%5D=Subject&type0%5B%5D=Subject&type0%5B%5D=Subject&type0%5B%5D=Subject&type0%5B%5D=Subject&sortControlElement=sortControlElement&sort=publishDateSort+desc
    - 'Wirtschaft und Recht':
        url: https://www.swissbib.ch/Search/Results?sort=relevance&advancedSearchFormRequest=advancedSearchFormRequest&join=OR&bool0[]=OR&lookfor0[]=wirtschaftslehre&type0[]=Subject&lookfor0[]=rechtskundeunterricht&type0[]=Subject&lookfor0[]=rechtserziehung&type0[]=Subject&lookfor0[]=Wirtschafts-+und+Rechtslehre&type0[]=Subject&bool1[]=AND&lookfor1[]=wirtschaft&type1[]=Subject&lookfor1[]=Lehrmittel&type1[]=Subject&bool2[]=AND&lookfor2[]=wirtschaft&type2[]=Subject&lookfor2[]=lehrbuch&type2[]=Subject&lookfor2[]=&type2[]=AllFields&bool3[]=AND&lookfor3[]=wirtschaft&type3[]=Subject&lookfor3[]=schulbuch&type3[]=Subject
